/*
 * $PSLibId: Runtime Library Versin 3.0$
 */
/*
 * File:convert.h
 */
#ifndef _CONVERT_H
#define _CONVERT_H

extern unsigned int todigit();
extern double atof();
extern int atoi();
extern long atol();
extern double strtod();
extern long strtol();
extern unsigned long strtoul();
extern long labs();
extern char *itoa(int);

/*
extern int abs();
extern div_t div();
extern ldiv_t ldiv();
*/

#endif
